CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    app       VARCHAR                     NOT NULL,
    uri       VARCHAR                     NOT NULL,
    ip        VARCHAR                     NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);

CREATE INDEX idx_app on endpoint_hits (app);
CREATE INDEX idx_ip on endpoint_hits (ip);
CREATE INDEX idx_uri on endpoint_hits (uri);
CREATE INDEX idx_timestamp on endpoint_hits (timestamp);
CREATE INDEX idx_uri_timestamp on endpoint_hits(uri, timestamp);