version: '3.1'
services:
  stats-server:
    build: ewm-stats/service
    container_name: ewm_stats_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:12.14-alpine
    container_name: ewm_stats_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ewm-main/
    container_name: ewm_main_container
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - EWM_STATS_SERVICE_URL=http://stats-server:9090
      - EWM_APP_NAME=ewm-main

  ewm-db:
    image: postgres:12.14-alpine
    container_name: ewm_main_db_container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root